// code was generated by deepseek and manually proofread

#include <Rcpp.h>
#include <unordered_set>

#include "hash_set.h"

// [[Rcpp::export]]
Rcpp::XPtr<CharSXPSet> cpp_hash_set_create(Rcpp::CharacterVector keys) {
    CharSXPSet* set = new CharSXPSet();
    set->max_load_factor(0.7);
    
    int n = keys.size();
    if(n > 0) {
        set->reserve(n);
        
        for(int i = 0; i < n; i++) {
            SEXP key = STRING_ELT(keys, i);
            auto result = set->emplace(key);
            if(!result.second) {
                std::string duplicate_key = CHAR(key);
                Rcpp::stop("Duplicate key found: " + duplicate_key);
            }
        }
    }
    
    return Rcpp::XPtr<CharSXPSet>(set);
}

// [[Rcpp::export]]
Rcpp::LogicalVector cpp_hash_set_exists(Rcpp::XPtr<CharSXPSet> ptr, Rcpp::CharacterVector keys) {
    if(!ptr) {
        Rcpp::stop("Invalid external pointer.");
    }
    
    CharSXPSet* set = ptr.get();
    int n = keys.size();
    Rcpp::LogicalVector result(n);
    
    for(int i = 0; i < n; i++) {
        SEXP key = STRING_ELT(keys, i);
        auto it = set->find(key);
        result[i] = (it != set->end());
    }
    
    return result;
}

// [[Rcpp::export]]
void cpp_hash_set_insert(Rcpp::XPtr<CharSXPSet> ptr, Rcpp::CharacterVector keys) {
    if (!ptr) {
        Rcpp::stop("Invalid external pointer.");
    }
    
    CharSXPSet* set = ptr.get();
    int n = keys.size();
    
    if(n > 0) {
        set->reserve(set->size() + n);
        for(int i = 0; i < n; i++) {
            set->insert(STRING_ELT(keys, i));
        }
    }
}

// [[Rcpp::export]]
int cpp_hash_set_size(Rcpp::XPtr<CharSXPSet> ptr) {
    if(!ptr) {
        Rcpp::stop("Invalid external pointer.");
    }
    return ptr->size();
}

// [[Rcpp::export]]
Rcpp::XPtr<CharSXPSet> cpp_hash_set_copy(Rcpp::XPtr<CharSXPSet> ptr) {
    if(!ptr) {
        Rcpp::stop("Invalid external pointer.");
    }
    
    CharSXPSet* original = ptr.get();
    
    CharSXPSet* copy = new CharSXPSet();
    copy->max_load_factor(0.7);
    copy->reserve(original->size());
    
    for(const SEXP& key : *original) {
        copy->insert(key);
    }
    
    return Rcpp::XPtr<CharSXPSet>(copy);
}

// [[Rcpp::export]]
Rcpp::CharacterVector cpp_hash_set_all_keys(Rcpp::XPtr<CharSXPSet> ptr) {
    if (!ptr) {
        Rcpp::stop("Invalid external pointer.");
    }
    
    CharSXPSet* set = ptr.get();
    size_t n = set->size();
    
    Rcpp::CharacterVector result(n);
    
    size_t i = 0;
    for(const SEXP& key : *set) {
        result[i] = key;
        i++;
    }
    
    return result;
}

// [[Rcpp::export]]
void cpp_hash_set_clear(Rcpp::XPtr<CharSXPSet> ptr) {
    if(!ptr) {
        Rcpp::stop("Invalid external pointer.");
    }
    ptr->clear();
}

// [[Rcpp::export]]
void cpp_hash_set_delete(Rcpp::XPtr<CharSXPSet> ptr, Rcpp::CharacterVector keys) {
    if(!ptr) {
        Rcpp::stop("Invalid external pointer.");
    }
    
    CharSXPSet* set = ptr.get();
    int n = keys.size();
    
    for(int i = 0; i < n; i++) {
        SEXP key = STRING_ELT(keys, i);
        size_t erased = set->erase(key);
        if (erased == 0) {
            std::string key_str = CHAR(key);
            Rcpp::stop("Key not found: " + key_str);
        }
    }
    
}
