# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_hash_env_table_create_int <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_env_table_create_int`, keys, values)
}

cpp_hash_env_table_create_double <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_env_table_create_double`, keys, values)
}

cpp_hash_env_table_create_bool <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_env_table_create_bool`, keys, values)
}

cpp_hash_env_table_create_string <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_env_table_create_string`, keys, values)
}

cpp_hash_env_table_create_date <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_env_table_create_date`, keys, values)
}

cpp_hash_env_table_create_time <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_env_table_create_time`, keys, values)
}

cpp_hash_env_table_create_list <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_env_table_create_list`, keys, values)
}

cpp_hash_env_table_insert_int <- function(env, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_env_table_insert_int`, env, keys, values))
}

cpp_hash_env_table_insert_double <- function(env, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_env_table_insert_double`, env, keys, values))
}

cpp_hash_env_table_insert_bool <- function(env, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_env_table_insert_bool`, env, keys, values))
}

cpp_hash_env_table_insert_string <- function(env, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_env_table_insert_string`, env, keys, values))
}

cpp_hash_env_table_insert_date <- function(env, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_env_table_insert_date`, env, keys, values))
}

cpp_hash_env_table_insert_time <- function(env, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_env_table_insert_time`, env, keys, values))
}

cpp_hash_env_table_insert_list <- function(env, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_env_table_insert_list`, env, keys, values))
}

cpp_hash_env_exists <- function(env, keys) {
    .Call(`_hashtable_cpp_hash_env_exists`, env, keys)
}

cpp_hash_env_size <- function(env) {
    .Call(`_hashtable_cpp_hash_env_size`, env)
}

cpp_hash_env_clear <- function(env) {
    invisible(.Call(`_hashtable_cpp_hash_env_clear`, env))
}

cpp_hash_env_delete <- function(env, keys) {
    invisible(.Call(`_hashtable_cpp_hash_env_delete`, env, keys))
}

cpp_hash_env_copy <- function(env) {
    .Call(`_hashtable_cpp_hash_env_copy`, env)
}

cpp_hash_env_keys <- function(env) {
    .Call(`_hashtable_cpp_hash_env_keys`, env)
}

cpp_hash_env_table_all_values_int <- function(env) {
    .Call(`_hashtable_cpp_hash_env_table_all_values_int`, env)
}

cpp_hash_env_table_all_values_double <- function(env) {
    .Call(`_hashtable_cpp_hash_env_table_all_values_double`, env)
}

cpp_hash_env_table_all_values_string <- function(env) {
    .Call(`_hashtable_cpp_hash_env_table_all_values_string`, env)
}

cpp_hash_env_table_all_values_bool <- function(env) {
    .Call(`_hashtable_cpp_hash_env_table_all_values_bool`, env)
}

cpp_hash_env_table_all_values_date <- function(env) {
    .Call(`_hashtable_cpp_hash_env_table_all_values_date`, env)
}

cpp_hash_env_table_all_values_time <- function(env) {
    .Call(`_hashtable_cpp_hash_env_table_all_values_time`, env)
}

cpp_hash_env_table_all_values_list <- function(env) {
    .Call(`_hashtable_cpp_hash_env_table_all_values_list`, env)
}

cpp_hash_env_table_values_int <- function(env, keys) {
    .Call(`_hashtable_cpp_hash_env_table_values_int`, env, keys)
}

cpp_hash_env_table_values_double <- function(env, keys) {
    .Call(`_hashtable_cpp_hash_env_table_values_double`, env, keys)
}

cpp_hash_env_table_values_string <- function(env, keys) {
    .Call(`_hashtable_cpp_hash_env_table_values_string`, env, keys)
}

cpp_hash_env_table_values_bool <- function(env, keys) {
    .Call(`_hashtable_cpp_hash_env_table_values_bool`, env, keys)
}

cpp_hash_env_table_values_date <- function(env, keys) {
    .Call(`_hashtable_cpp_hash_env_table_values_date`, env, keys)
}

cpp_hash_env_table_values_time <- function(env, keys) {
    .Call(`_hashtable_cpp_hash_env_table_values_time`, env, keys)
}

cpp_hash_env_table_values_list <- function(env, keys) {
    .Call(`_hashtable_cpp_hash_env_table_values_list`, env, keys)
}

cpp_update_vector_elements <- function(x, ind, values) {
    invisible(.Call(`_hashtable_cpp_update_vector_elements`, x, ind, values))
}

cpp_hash_set_create <- function(keys) {
    .Call(`_hashtable_cpp_hash_set_create`, keys)
}

cpp_hash_set_exists <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_set_exists`, ptr, keys)
}

cpp_hash_set_insert <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_set_insert`, ptr, keys))
}

cpp_hash_set_size <- function(ptr) {
    .Call(`_hashtable_cpp_hash_set_size`, ptr)
}

cpp_hash_set_copy <- function(ptr) {
    .Call(`_hashtable_cpp_hash_set_copy`, ptr)
}

cpp_hash_set_all_keys <- function(ptr) {
    .Call(`_hashtable_cpp_hash_set_all_keys`, ptr)
}

cpp_hash_set_clear <- function(ptr) {
    invisible(.Call(`_hashtable_cpp_hash_set_clear`, ptr))
}

cpp_hash_set_delete <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_set_delete`, ptr, keys))
}

cpp_intersect_to_list <- function(ptr, lt) {
    .Call(`_hashtable_cpp_intersect_to_list`, ptr, lt)
}

cpp_hash_table_create_int <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_table_create_int`, keys, values)
}

cpp_hash_table_exists_int <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_exists_int`, ptr, keys)
}

cpp_hash_table_values_int <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_values_int`, ptr, keys)
}

cpp_hash_table_insert_int <- function(ptr, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_table_insert_int`, ptr, keys, values))
}

cpp_hash_table_size_int <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_size_int`, ptr)
}

cpp_hash_table_copy_int <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_copy_int`, ptr)
}

cpp_hash_table_all_keys_int <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_keys_int`, ptr)
}

cpp_hash_table_all_values_int <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_values_int`, ptr)
}

cpp_hash_table_clear_int <- function(ptr) {
    invisible(.Call(`_hashtable_cpp_hash_table_clear_int`, ptr))
}

cpp_hash_table_delete_int <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_table_delete_int`, ptr, keys))
}

cpp_hash_table_create_double <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_table_create_double`, keys, values)
}

cpp_hash_table_exists_double <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_exists_double`, ptr, keys)
}

cpp_hash_table_values_double <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_values_double`, ptr, keys)
}

cpp_hash_table_insert_double <- function(ptr, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_table_insert_double`, ptr, keys, values))
}

cpp_hash_table_size_double <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_size_double`, ptr)
}

cpp_hash_table_copy_double <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_copy_double`, ptr)
}

cpp_hash_table_all_keys_double <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_keys_double`, ptr)
}

cpp_hash_table_all_values_double <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_values_double`, ptr)
}

cpp_hash_table_clear_double <- function(ptr) {
    invisible(.Call(`_hashtable_cpp_hash_table_clear_double`, ptr))
}

cpp_hash_table_delete_double <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_table_delete_double`, ptr, keys))
}

cpp_hash_table_create_string <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_table_create_string`, keys, values)
}

cpp_hash_table_exists_string <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_exists_string`, ptr, keys)
}

cpp_hash_table_values_string <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_values_string`, ptr, keys)
}

cpp_hash_table_insert_string <- function(ptr, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_table_insert_string`, ptr, keys, values))
}

cpp_hash_table_size_string <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_size_string`, ptr)
}

cpp_hash_table_copy_string <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_copy_string`, ptr)
}

cpp_hash_table_all_keys_string <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_keys_string`, ptr)
}

cpp_hash_table_all_values_string <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_values_string`, ptr)
}

cpp_hash_table_clear_string <- function(ptr) {
    invisible(.Call(`_hashtable_cpp_hash_table_clear_string`, ptr))
}

cpp_hash_table_delete_string <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_table_delete_string`, ptr, keys))
}

cpp_hash_table_create_bool <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_table_create_bool`, keys, values)
}

cpp_hash_table_exists_bool <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_exists_bool`, ptr, keys)
}

cpp_hash_table_values_bool <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_values_bool`, ptr, keys)
}

cpp_hash_table_insert_bool <- function(ptr, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_table_insert_bool`, ptr, keys, values))
}

cpp_hash_table_size_bool <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_size_bool`, ptr)
}

cpp_hash_table_copy_bool <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_copy_bool`, ptr)
}

cpp_hash_table_all_keys_bool <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_keys_bool`, ptr)
}

cpp_hash_table_all_values_bool <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_values_bool`, ptr)
}

cpp_hash_table_clear_bool <- function(ptr) {
    invisible(.Call(`_hashtable_cpp_hash_table_clear_bool`, ptr))
}

cpp_hash_table_delete_bool <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_table_delete_bool`, ptr, keys))
}

cpp_hash_table_create_date <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_table_create_date`, keys, values)
}

cpp_hash_table_exists_date <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_exists_date`, ptr, keys)
}

cpp_hash_table_values_date <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_values_date`, ptr, keys)
}

cpp_hash_table_insert_date <- function(ptr, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_table_insert_date`, ptr, keys, values))
}

cpp_hash_table_size_date <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_size_date`, ptr)
}

cpp_hash_table_copy_date <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_copy_date`, ptr)
}

cpp_hash_table_all_keys_date <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_keys_date`, ptr)
}

cpp_hash_table_all_values_date <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_values_date`, ptr)
}

cpp_hash_table_clear_date <- function(ptr) {
    invisible(.Call(`_hashtable_cpp_hash_table_clear_date`, ptr))
}

cpp_hash_table_delete_date <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_table_delete_date`, ptr, keys))
}

cpp_hash_table_create_time <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_table_create_time`, keys, values)
}

cpp_hash_table_exists_time <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_exists_time`, ptr, keys)
}

cpp_hash_table_values_time <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_values_time`, ptr, keys)
}

cpp_hash_table_insert_time <- function(ptr, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_table_insert_time`, ptr, keys, values))
}

cpp_hash_table_size_time <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_size_time`, ptr)
}

cpp_hash_table_copy_time <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_copy_time`, ptr)
}

cpp_hash_table_all_keys_time <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_keys_time`, ptr)
}

cpp_hash_table_all_values_time <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_values_time`, ptr)
}

cpp_hash_table_clear_time <- function(ptr) {
    invisible(.Call(`_hashtable_cpp_hash_table_clear_time`, ptr))
}

cpp_hash_table_delete_time <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_table_delete_time`, ptr, keys))
}

cpp_hash_table_create_list <- function(keys, values) {
    .Call(`_hashtable_cpp_hash_table_create_list`, keys, values)
}

cpp_hash_table_exists_list <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_exists_list`, ptr, keys)
}

cpp_hash_table_values_list <- function(ptr, keys) {
    .Call(`_hashtable_cpp_hash_table_values_list`, ptr, keys)
}

cpp_hash_table_insert_list <- function(ptr, keys, values) {
    invisible(.Call(`_hashtable_cpp_hash_table_insert_list`, ptr, keys, values))
}

cpp_hash_table_size_list <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_size_list`, ptr)
}

cpp_hash_table_copy_list <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_copy_list`, ptr)
}

cpp_hash_table_all_keys_list <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_keys_list`, ptr)
}

cpp_hash_table_all_values_list <- function(ptr) {
    .Call(`_hashtable_cpp_hash_table_all_values_list`, ptr)
}

cpp_hash_table_clear_list <- function(ptr) {
    invisible(.Call(`_hashtable_cpp_hash_table_clear_list`, ptr))
}

cpp_hash_table_delete_list <- function(ptr, keys) {
    invisible(.Call(`_hashtable_cpp_hash_table_delete_list`, ptr, keys))
}

